- name: Install courgettes
  hosts: courgettes-debian
  vars:
    destination: '/home/{{ansible_user}}/gits/egj'
    nginx_proxy_location: '/home/{{ansible_user}}/gits/nginx-proxy-generator'
    default_port: "8000"
    deploy_port: "8333"
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{destination}}"
        state: directory
        mode: '0755'
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: docker-compose/egj.docker-compose.yaml
        dest: '{{ destination }}/docker-compose.yaml'
        owner: '{{ansible_user}}'
        group: '{{ansible_user}}'
    - name: Launch container
      shell: |
        docker-compose -f docker-compose.yaml down
        docker-compose -f docker-compose.yaml up -d
      args:
        chdir: '{{ destination }}'
    - name: Create proxy to egj2021.courgettes.club
      become: true
      become_method: sudo
      expect:
        command: ./generate.sh egj2021.courgettes.club http://localhost:{{ deploy_port }}
        responses:
          Press enter to continue.: ''
          Select the appropriate number \[1-2\] then \[enter\]: 1
          email address: 'nichuguen@gmail.com'
        chdir: '{{ nginx_proxy_location }}'