- name: Install courgettes
  hosts: courgettes-debian
  vars:
    destination: '/home/{{ansible_user}}/gits/courgettes'
    nginx_proxy_location: '/home/{{ansible_user}}/gits/nginx-proxy-generator'
    default_port: "8000"
    deploy_port: "8006"
    GITHUB_ANSIBLE_TOKEN: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61316238396336326333666663633462336539333266646137643135663164313731653064323335
      3239346136636633613930616330626639376231323861630a643665313639343936376639646363
      31313535643762313262393137643261383466626533666131336434613431316364303466396136
      3663646666373665310a343763383539356662303734306334616664393233666566666635383235
      61663864366265343034353737653339313839383037616266656364343735393334306431373061
      3963366634623034313732663833636564613561663432633430
  tasks:
    - name: Pull git
      git:
        repo: 'https://ymaktepi:{{GITHUB_ANSIBLE_TOKEN}}@github.com/ymaktepi/CourgetteSite.git'
        dest: '{{ destination }}'
    - name: Copy config file
      shell: |
          cp docker-compose-example.yml docker-compose.yml
      args:
        chdir: '{{ destination }}'
    # Not using the docker_compose module because it requires the python package installed on the host
    - name: Change ports in config
      replace:
        path: '{{destination}}/docker-compose.yml'
        regexp: '{{default_port}}'
        replace: '{{deploy_port}}'
    - name: Launch container
      shell: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d
      args: 
        chdir: '{{ destination }}'
    - name: Create proxy to courgettes.club
      become: true
      become_method: sudo
      expect:
          command: ./generate.sh courgettes.club http://localhost:{{ deploy_port }}
          responses:
              Press enter to continue.: ''
              Select the appropriate number \[1-2\] then \[enter\]: 1
              email address: 'nichuguen@gmail.com'
          chdir: '{{ nginx_proxy_location }}'
    - name: Create proxy to www.courgettes.club
      become: true
      become_method: sudo
      expect:
          command: ./generate.sh www.courgettes.club http://localhost:{{ deploy_port }}
          responses:
              Press enter to continue.: ''
              Select the appropriate number \[1-2\] then \[enter\]: 1
              email address: 'nichuguen@gmail.com'
          chdir: '{{ nginx_proxy_location }}'
